version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: trello-dynamodb
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - trello-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trello-backend
    ports:
      - "4000:4000"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - dynamodb-local
    networks:
      - trello-network
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trello-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GRAPHQL_ENDPOINT=http://localhost:4000/graphql
    depends_on:
      - backend
    networks:
      - trello-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  trello-network:
    driver: bridge